### ISSUE TITLE
Vitamio 5 Notification from Google Play

### ISSUE THREAD

**Issue by jimztercrack** [yixia/VitamioBundle#367]
Hello! I already update my project to vitamio 5 from: https://www.vitamio.org/en/Download/   but I can't update my app in google play  they still say that my app have vulnerabilities, can someone help me wit this issue please; thanks.

This is the notification from google play:  

Hello Google Play Developer,

We rejected , with package name , for violating our Malicious Behavior policy. If you submitted an update, the previous version of your app is still available on Google Play.

This app uses software that contains security vulnerabilities for users.

Below is the list of vulnerabilities and the corresponding APK versions that were detected in your recent submission. Please upgrade your app(s) as soon as possible and increment the version number of the upgraded APK.
Vulnerability   APK Version(s)
Vitamio

The vulnerabilities were fixed in Vitamio v.5.0 and higher. To confirm the vulnerability, check to see if your SDK includes libs/armeabi-v7a/libvinit.so or libs/armeabi/libvinit.so. If either file is present, the SDK needs to be upgraded.

You can find more information and next steps in this Google Help Center article.
    4

To confirm you’ve upgraded correctly, submit the updated version of your app to the Developer Console and check back after five hours to make sure the warning is gone.

While these vulnerabilities may not affect every app that uses this software, it’s best to stay up to date on all security patches. Make sure to update any libraries in your app that have known security issues, even if you're not sure the issues are relevant to your app.

Apps must also comply with the Developer Distribution Agreement and Developer Program Policies.

If you feel we have made this determination in error, please reach out to our policy support team through the Google Play Developer Help Center.

Best,

The Google Play Team

**Comment by MythodeaLoL** [comment]
@jimztercrack 
~~Please post here~~:
#360 ~~Vitamio 5.0.0 Google Play warning: You are using a vulnerable version of OpenSSL~~ **(Closed)**
~~all are focusing the subject here.~~

**Comment by jimztercrack** [comment]
ok thanks

**Comment by crossle** [comment]
@wchengyu please update OpenSSL

**Comment by kadriengin** [comment]
We continue from here. we are waiting new version of vitamio

**Comment by juanmaa16** [comment]
We continue waiting for update.

**Comment by kadriengin** [comment]
yes still we are waitingggg

**Comment by ninenox** [comment]
ok,I'm waiting too.

**Comment by MythodeaLoL** [comment]
:fire: I built a version without the librtmp and `OpenSSL` for people who do not use it, I will publish in a few hours/day.

The version with `OpenSSL 1.0.2g` depends on some archive that are not being generated, I'm trying to solve it, it is the best I can do until it comes a official version.

**We will continue waiting.**
  https://github.com/yixia/VitamioBundle/issues/371

> Florida

**Comment by kadriengin** [comment]
Why the fucking vitamio dont listen us! Many people wait for it but why it dont interest with us!.....

**Comment by jimztercrack** [comment]
Someone  know if am I going to have the same problem with vitamio in app store?  Because I want to built app for iphone and ipad with vitamio

**Comment by kadriengin** [comment]
@jimztercrack  now i have an app in app store with vitamio. It dont have a problem.

**Comment by MythodeaLoL** [comment]
@kadriengin you app have OpenSSL?

**Comment by kadriengin** [comment]
I dont know does ios version have openssl or not!

**Comment by MythodeaLoL** [comment]
**Build Status: ([RealTime](https://github.com/VitamioCustom/VitamioBundle_422/blob/master/README.md))**
I have gotten great progress in bug fixing compiling, basically [2/3] are concluded, missing only write the command line to compile the librtmp.

> **Versions are used `FFmpeg 3.0.1`, `rtmpdump`/`librtmp 2.4` and `OpenSSL 1.0.2g`.**

We have a version tomorrow perhaps, or on the weekend, if all libraries fit.

If [vitamio team update](https://github.com/yixia/VitamioBundle/issues/367#issuecomment-209167455), all right, I will continue to build this library/_update_ if not, this can be a real alternative, since it i can always compile the latest versions of OpenSSL/FFmpeg.
I hope to get lucky ... :four_leaf_clover:  bye

**Comment by shinayser** [comment]
There is any advance in this, guys?

**Comment by FloridaStream** [comment]
Build has failed for _armeabi_ ARCH.
`libswscale/swscale_unscaled.o:swscale_unscaled.c:function ff_get_unscaled_swscale: error: undefined reference to 'ff_get_unscaled_swscale_arm'`

I'm trying to fix this problem to publish a PRE-Release
The new ffmpeg contains countless problems when compiling for android.

> x86 has no problems.
> mips no tested yet.

**Comment by MythodeaLoL** [comment]
##### `Vitamio 4.2.2` **and** `Vitamio 5.0.0` **PRE-Release**

> https://github.com/VitamioCustom/VitamioUpdates

Version untested, may contain errors.
If you need some encode or ffmpeg functions, open an issue with the parameter to enable it.

A positive or negative feedback operation is welcome so that there may be future updates.

Details are present in the repository.
_Good luck for all of us_. :+1:

**Comment by jimztercrack** [comment]
if anyone need to test their application you can use pcloudy.com they provides a real time access to diferent physical android and ios devices using just a browser.

**Comment by MythodeaLoL** [comment]
> **COMPATIBILITY PROBLEMS FOUND**

The problem is the compilation of libvplayer.so made by vitamio team, the version used by them is lower than that used by me, so it is giving conflict, the only alternative is to use the version they used to compile the libvplayer.so ffmpeg 2.0, since I do not have the sourde the libvplayer.so to compile with the new ffmpeg 3.0

<br>

> **Vitamio Official Update for OpenSSL issue**

http://wscdn.miaopai.com/download/VitamioBundle-5.0.1.zip (https://www.vitamio.org/Download/)
**Stay tuned, this update disables the OpenSSL**
<BR>

> #### *EDIT:
- [x] I will compile a new version in some days with ffmpeg 2.0 used by vitamio, to fix this issue. =)
- [x] Compiled and Uploaded 

## New Version available https://github.com/VitamioCustom/VitamioUpdates

**Comment by FloridaStream** [comment]
updated

**Comment by kenchan97** [comment]
@FloridaStream i use vitamio 5.01 and replaced https://github.com/VitamioCustom/VitamioUpdates/tree/master/Vitamio_5%2B/libs to 5.01 libs folder .
but the player show me SIGSEGV error .........

**Comment by MythodeaLoL** [comment]
https://github.com/yixia/VitamioBundle/issues/360#issuecomment-217954430

**Comment by MythodeaLoL** [comment]
I can not buy an account on Google Play Developers have an account there so much easier for me to help better and test. If any of you have any account there you no longer use and can give me, I would be grateful. I'm trying to achieve, but it is complicated.

One problem may be the `libvinit.so` perhaps updating the sdk vitamio 4 to use the libs vitamio 5, and the corrections of OpenSSL can solve, however I have no way to prove this theory. Now when I get some account in Google Play I can help more, which can take many months.

> In short, play google does not accept `libvinit.so` and OpenSSL outdated.

**Comment by MythodeaLoL** [comment]
I'm converting my version  `4.2.2` to version `5.0.1`, there are not many differences in `.java` basically what you may notice is the absence of `libarm.so` and `libvinit.so` file, and some changes in the loading of libraries I hope it all works out in the end. I keep you informed of my journey.
@Akiracr @mistrydarshan99 @kadriengin 

Vitamio 5.0.1 use `FFmpeg version n2.8.6-11-gf9f9f31` and **OpenSSL** has **disabled**.
_I have much to study to get some progress._

**Comment by MythodeaLoL** [comment]
## I'm giving up the vitamio, I will look for other options for players who use ffmpeg.

**Comment by kadriengin** [comment]
:/

**Comment by icastell** [comment]
@FloridaStream :( Do you know other options?

**Comment by ashwanigarg** [comment]
@FloridaStream I tried to run the vitamio 5.0.1 bundle it compiled successfully but it is not playing any video or audio. I am in trouble. I need to complete it as soon as possible. My app is rejected by play store because of use of Vitamio 4.

**Comment by jimztercrack** [comment]
Do you  tried with giraffe player @FloridaStream ? For me is working fine in Google play

**Comment by ashwanigarg** [comment]
@jimztercrack Hi, can u help me out. I am not able to compile the giraffe player sample project. It is giving me multidex errors. Please help me out and can you tell me the name of your play store app. 
Thanks,

**Comment by MythodeaLoL** [comment]
@jimztercrack _giraffe player_ supports _ffmpeg_ commands like _vitamio_? I need them to run.

I seem to be tied to vitamio, it would be beneficial if he turned an open source project.

**Comment by iosifnicolae2** [comment]
Guys, i used ExoPlayer and work very well..
My audio player start very fast and I don't have problems like Vitamio..

**Comment by kadriengin** [comment]
@iosifnicolae2 exoplayer's minSdk is problem and another problem is not supported rtmp

**Comment by iosifnicolae2** [comment]
@kadriengin 
https://github.com/ButterflyTV/ExoPlayer-with-RTMP-and-FLV-seek
ExoPlayer support RTMP

**Comment by IamWorkAndWork** [comment]
@iosifnicolae2 I have use ExoPlayer for a video it was quick and very good. but I did not know that ExoPlayer can support RTMP too. you make my day. thank you.

**Comment by ninenox** [comment]
Vitamio 5.0.1 is reject from playstore because APP UPDATE REJECTED

Your APK has been rejected for containing security vulnerabilities, which violates the Malicious Behavior policy. If you submitted an update, the previous version of your app is still live on Google Play.

**Comment by MythodeaLoL** [comment]
I found this project https://github.com/pedromfmachado/FFmpegMediaPlayer/blob/master/fmp-library/jni/player/ffmpeg_mediaplayer.c

This is a FFmpeg Media Player, It is very interesting, and is full open source.
If someone want to use and have some success, please inform us.

**Comment by kadriengin** [comment]
@iosifnicolae2  i know that project but it has some problems too. @nisit15  if you did not delete libraries under arm64 folder, google reject vitamio 5.0.1 . You must delete arm64 folder.
