### ISSUE TITLE
Playing RTMP on Android boxes (4.2 or 4.4) gives blur picture

### ISSUE THREAD

**Issue by streamliveinfo** [yixia/VitamioBundle#371]
I am using Vitamio 5.0 and it works fine on my Samsung tablet Android 5.0. It plays RTMP streams from my site. However when I install the app on Android boxes, which I guess using Android 4.2 or 4.4, it gives blurry pictures. Those boxes are named gbox, mxbox and many other chinese boxes out there. Is it an issue with Vitamio that it can't play well on lower APIs like API 18 or lower? Is there a way to fix this issue?

![bad_rtmp](https://cloud.githubusercontent.com/assets/18544122/14656009/293572de-0653-11e6-8fa2-7bf0340759d9.jpg)

**Comment by allouch89** [comment]
I have the same problem on android set-top boxes, using android version 4.2, 4.4, 5.0, tested on 3 different models; CS918, MXQ and i68 chinese boxes. The streams works but the picture are blurry or the video is lagging/missing frames, the sound is working just fine.
Every now and then i come back to vitamio to check if there has been found a solution, but so far nothing, been looking for quite a while now.

**Comment by MythodeaLoL** [comment]
You can reproduce this problem at some emulator like genymotion for example?

Are you using some extra ffmpeg command or other parameters beyond the basic to call the stream?
Tried to enable/disable hardware acceleration?

**Comment by streamliveinfo** [comment]
I have also tested on another more expensive Android box which use better chip called rockchip rk3288. It works perfectly. I am 99% confident this is the problem with the hardware, like decoder, not the Android version. Gbox or MXbox uses cheap chip (not sure what it is) that can't decode the RTMp streams very well.

**Comment by allouch89** [comment]
I have tested with RTMP, HTTP(m3u8), RTSP, MMS, etc.
Also tried to change the quality of the stream, tried using HW and SW decoders, nothing was able to help me.

**Comment by MythodeaLoL** [comment]
@allouch89 @streamliveinfo I'm trying to compile the new version of ffmpeg 3.0 for updating the vitamio hopefully it can help you, hopefully.

**#Edit**

``` javascript
android-ndk-r11c/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: libavcodec/reverse.o: multiple definition of 'ff_reverse'
```

Compile of `ffmpeg 3.0` has failed **=(** i will continue trying to compile on `3.0`, but if it does not work, I have to use version `2.0`

Anyone else trying to compile? With the real version of openssl 1.0.2g could not in any way generate the folders of files `$SSL/obj/local/armeabi-v7a/objs/crypto` `objs/...` =( 

Just as `ffmpeg 3.0`, I can only use earlier versions `1.0.1e`, modified to look like `1.0.2g+`.
If vitamio team shared the OpenSSL files 1.0.2x used in the latest build, we could have a more updated version. But we are alone.

I do not know what to do.... :four_leaf_clover: 

https://github.com/yixia/VitamioBundle/issues/367

**Comment by streamliveinfo** [comment]
I am a little confused here. The issue with Vitamio now is bad quality playback on cheap Android boxes like Gbox, MXbox. Will the new compiled ffmpeg3.0 will help so the the issue? The Google Play issue is the openSSL

**Comment by MythodeaLoL** [comment]
Whether or not, it costs nothing to try, we will not ever know if we do not try, but I have seen that I can not help it, as I said above.

**Comment by allouch89** [comment]
@FloridaStream could you try to send me the compiled version with ffmpeg 2.0?
I would do it my self if i knew how but im simple too new at this to even try.

**Comment by MythodeaLoL** [comment]
Yes, I'll compile everything and send at once. We inform you when the files are ready. 
You really need the support rtmp?

**Comment by streamliveinfo** [comment]
I need it to support securetoken. Willl compiled ffmpeg will do it or I must compile with librtmp?

**Comment by MythodeaLoL** [comment]
In this case, you must compile with librtmp and add support to SecureToken.

**Comment by allouch89** [comment]
yes i need rtmp too, http streams works on all devices with default videoview so without the rtmp support its not necessary for me to use vitamio

**Comment by MythodeaLoL** [comment]
I Fucked the virtual machine in the build attempts and updates of the latest version of ffmpeg and openssl, result, compiling and sending the files will delay. Unfortunately. I'm almost giving up. Sorry.

**Comment by allouch89** [comment]
No problem, thanks for your effort:)

**Comment by djamiros** [comment]
Is what you have found a solution for this ?

**Comment by djamiros** [comment]
Solution:

mMediaPlayer.setVideoQuality(MediaPlayer.VIDEOQUALITY_HIGH);   
mMediaPlayer.getHolder().setFormat(PixelFormat.RGBX_8888);
